### ISSUE TITLE
fingerprint operation canceled - Then Throws Alert Saying Authentication Failed Cancelled

### ISSUE THREAD

**Issue by billycomic** [NiklasMerz/cordova-plugin-fingerprint-aio#108]
## Do you have a question ?

**Please go to [Gitter](https://gitter.im/cordova-plugin-fingerprint-aio) and ask here. Avoid submitting support requests as issues on Github. If you have trouble installing this plugin, please ask on Gitter first.**

## Description

* What did you do?
I am calling the Fingerprint.prototype.show() method.
* What did happen?
Sometimes it will wait and capture my fingerprint, but mostly the fingerprint modal states "Fingerprint Operation Canceled" and then closes and throws the alert from the App Code "Authentication Failed Cancelled"
* What did you expect to happen?
To always capture the fingerprint once the modal is launched and to wait, not cancel and throw error.
* Type of issue (bug, feature request)
bug

## Environment

* Plugin version
1.3.8
* Build environment (```cordova info```)
cordova -v 7.1.0
* ```cordova platform ls```
Installed platforms:
  android 6.3.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
### Logs
Not sure where to capture these logs.

**Comment by NiklasMerz** [comment]
Does this happen on Android or iOS? Could you please post some logs from the Javascript console, Xcode or Logcat?

**Comment by NiklasMerz** [comment]
I am closing this issue, because it is inactive for some time. If you still have this problem, feel free to contact developers on [Gitter](https://gitter.im/cordova-plugin-fingerprint-aio).

Thank you

**Comment by michael87** [comment]
I have some extra information:

`

11-07 16:37:50.012 25838 25941 V Fingerprint: Init Fingerprint
11-07 16:37:50.018 25838 25941 V Fingerprint: Fingerprint action: isAvailable
11-07 16:37:50.020 25838 25941 W CordovaPlugin: Attempted to send a second callback for ID: Fingerprint1482536722
11-07 16:37:50.020 25838 25941 W CordovaPlugin: Result was: "finger"
11-07 16:37:50.043 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.044 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:50.070 25838 25945 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-07 16:37:50.113 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.133 25838 25838 D SystemWebChromeClient: file:///android_asset/www/js/jquery.mobileapp.js: Line 1308 : Uncaught TypeError: window.FirebasePlugin.clearAllNotifications is not a function
11-07 16:37:50.133 25838 25838 I chromium: [INFO:CONSOLE(1308)] "Uncaught TypeError: window.FirebasePlugin.clearAllNotifications is not a function", source: file:///android_asset/www/js/jquery.mobileapp.js (1308)
11-07 16:37:50.137 25838 25895 E AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/images/logo-128.png
11-07 16:37:50.138 25838 25895 E AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/images/logo-192.png
11-07 16:37:50.198 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.208 25838 25838 D CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
11-07 16:37:50.294 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.348 25838 25941 V Fingerprint: Fingerprint action: authenticate
11-07 16:37:50.353  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.353  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.353  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.358  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.358  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.358  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.361 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.361  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.361  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.361  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.363  1386  1386 D TrustyKeymaster: Device received add_rng_entropy
11-07 16:37:50.364  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 20 msg size 24
11-07 16:37:50.364  1386  1386 E TrustyKeymaster: Received 4 byte response
11-07 16:37:50.365  1386  1386 D TrustyKeymaster: Device received begin
11-07 16:37:50.365  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 229 msg size 233
11-07 16:37:50.366  1386  1386 E TrustyKeymaster: Received 52 byte response
11-07 16:37:50.369  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.369  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.370  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.383 25838 25941 W PluginManager: THREAD WARNING: exec() call to Fingerprint.authenticate blocked the main thread for 36ms. Plugin should use CordovaInterface.getThreadPool().
11-07 16:37:50.434 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.452 25838 25838 D SystemWebChromeClient: file:///android_asset/www/bower_components/jquery/dist/jquery.js: Line 9064 : Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
11-07 16:37:50.452 25838 25838 I chromium: [INFO:CONSOLE(9064)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: file:///android_asset/www/bower_components/jquery/dist/jquery.js (9064)
11-07 16:37:50.459  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.459  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.460  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.465  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.465  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.465  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.467  1386  1386 D TrustyKeymaster: Device received add_rng_entropy
11-07 16:37:50.467  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 20 msg size 24
11-07 16:37:50.468  1386  1386 E TrustyKeymaster: Received 4 byte response
11-07 16:37:50.468  1386  1386 D TrustyKeymaster: Device received begin
11-07 16:37:50.468  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 229 msg size 233
11-07 16:37:50.468  1386  1386 E TrustyKeymaster: Received 52 byte response
11-07 16:37:50.473  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.473  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.473  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.526 25838 25941 V Fingerprint: Fingerprint action: isAvailable
11-07 16:37:50.527 25838 25843 I zygote  : Do partial code cache collection, code=61KB, data=57KB
11-07 16:37:50.527  1386  1386 D TrustyKeymaster: Device received abort
11-07 16:37:50.527  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 8 msg size 12
11-07 16:37:50.527  1386  1386 E TrustyKeymaster: Received 4 byte response
11-07 16:37:50.527 25838 25941 W CordovaPlugin: Attempted to send a second callback for ID: Fingerprint1482536729
11-07 16:37:50.527 25838 25941 W CordovaPlugin: Result was: "finger"
11-07 16:37:50.529 25838 25843 I zygote  : After code cache collection, code=61KB, data=57KB
11-07 16:37:50.529 25838 25843 I zygote  : Increasing code cache capacity to 256KB
11-07 16:37:50.544 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.550 25838 25838 D FingerprintAuthDialog: disableBackup: true
11-07 16:37:50.598  1580  1580 D FingerprintHal: ----------------> fingerprint_get_auth_id ----------------->
11-07 16:37:50.598  1580  1580 D FingerprintHal: ----------------> fingerprint_get_auth_id auth id 6b8b4567327b23c6----------------->
11-07 16:37:50.598  1697  1697 V FingerprintService: startAuthentication(nl.demo.customer)
11-07 16:37:50.598  1697  1697 V FingerprintService: starting client AuthenticationClient(nl.demo.customer), initiatedByClient = true)
11-07 16:37:50.598  1697  1697 W FingerprintService: client nl.demo.customer is authenticating...
11-07 16:37:50.613 25838 25941 V Fingerprint: Fingerprint action: authenticate
11-07 16:37:50.617 25838 25843 I zygote  : Do full code cache collection, code=63KB, data=80KB
11-07 16:37:50.617 25838 25843 I zygote  : After code cache collection, code=49KB, data=49KB
11-07 16:37:50.618  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.619  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.619  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.621  1439  2118 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5804032
11-07 16:37:50.621  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.621  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.621  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.624  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.624  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.624  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.625  1386  1386 D TrustyKeymaster: Device received add_rng_entropy
11-07 16:37:50.625  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 20 msg size 24
11-07 16:37:50.625  1386  1386 E TrustyKeymaster: Received 4 byte response
11-07 16:37:50.626  1386  1386 D TrustyKeymaster: Device received begin
11-07 16:37:50.626  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 229 msg size 233
11-07 16:37:50.626  1386  1386 E TrustyKeymaster: Received 52 byte response
11-07 16:37:50.627  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.627  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.628  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.628  1439 17048 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5804032
11-07 16:37:50.630 25838 25941 W PluginManager: THREAD WARNING: exec() call to Fingerprint.authenticate blocked the main thread for 17ms. Plugin should use CordovaInterface.getThreadPool().
11-07 16:37:50.634  1439 17048 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5804032
11-07 16:37:50.694  1386  1386 D TrustyKeymaster: Device received abort
11-07 16:37:50.694  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 8 msg size 12
11-07 16:37:50.694  1386  1386 E TrustyKeymaster: Received 4 byte response
11-07 16:37:50.726 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.738 25838 25838 D SystemWebChromeClient: file:///android_asset/www/index.html: Line 76 : Initializing without device :(
11-07 16:37:50.738 25838 25838 I chromium: [INFO:CONSOLE(76)] "Initializing without device :(", source: file:///android_asset/www/index.html (76)
11-07 16:37:50.740 25838 25838 D SystemWebChromeClient: file:///android_asset/www/js/jquery.mobileapp.js: Line 1308 : Uncaught TypeError: window.FirebasePlugin.clearAllNotifications is not a function
11-07 16:37:50.740 25838 25838 I chromium: [INFO:CONSOLE(1308)] "Uncaught TypeError: window.FirebasePlugin.clearAllNotifications is not a function", source: file:///android_asset/www/js/jquery.mobileapp.js (1308)
11-07 16:37:50.772 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:50.784 24604 25320 W ctxmgr  : [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10013):IndoorOutdoorProducer, vrsn=12874000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 24604). Was: 3 for 57, account#-517948760#
11-07 16:37:50.892 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:50.896 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:50.909  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.909  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.909  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.912  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.912  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.913  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.915  1386  1386 D TrustyKeymaster: Device received add_rng_entropy
11-07 16:37:50.915  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 20 msg size 24
11-07 16:37:50.915  1386  1386 E TrustyKeymaster: Received 4 byte response
11-07 16:37:50.916  1386  1386 D TrustyKeymaster: Device received begin
11-07 16:37:50.917  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 229 msg size 233
11-07 16:37:50.917  1386  1386 E TrustyKeymaster: Received 52 byte response
11-07 16:37:50.919  1386  1386 D TrustyKeymaster: Device received get_key_characteristics
11-07 16:37:50.919  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 201 msg size 205
11-07 16:37:50.921  1386  1386 E TrustyKeymaster: Received 160 byte response
11-07 16:37:50.940 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:50.967  1386  1386 D TrustyKeymaster: Device received abort
11-07 16:37:50.967  1386  1386 E TrustyKeymaster: calling trusty_keymaster_call insize 8 msg size 12
11-07 16:37:50.967  1386  1386 E TrustyKeymaster: Received 4 byte response
11-07 16:37:51.019 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:51.027 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:51.063 25838 25838 D FingerprintAuthDialog: disableBackup: true
11-07 16:37:51.133  1580  1580 D FingerprintHal: ----------------> fingerprint_get_auth_id ----------------->
11-07 16:37:51.133  1580  1580 D FingerprintHal: ----------------> fingerprint_get_auth_id auth id 6b8b4567327b23c6----------------->
11-07 16:37:51.133  1697  1697 V FingerprintService: startAuthentication(nl.demo.customer)
11-07 16:37:51.133  1697  1697 V FingerprintService: request stop current client nl.demo.customer
11-07 16:37:51.134  1580  1580 D FingerprintHal: ----------------> fingerprint_cancel ----------------->
11-07 16:37:51.134  1580  1580 D android.hardware.biometrics.fingerprint@2.1-service: onError(5)
11-07 16:37:51.135  1697  1697 W FingerprintService: client nl.demo.customer is no longer authenticating
11-07 16:37:51.136  1697  1697 V FingerprintService: Done with client: nl.demo.customer
11-07 16:37:51.136  1697  1697 V FingerprintService: handleError(client=nl.demo.customer, error = 5)
11-07 16:37:51.136  1697  1697 V FingerprintService: start pending client nl.demo.customer
11-07 16:37:51.136  1697  1697 V FingerprintService: starting client AuthenticationClient(nl.demo.customer), initiatedByClient = false)
11-07 16:37:51.137  1697  1697 W FingerprintService: client nl.demo.customer is authenticating...
11-07 16:37:51.201 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:51.276  1450  1450 D SurfaceFlinger: duplicate layer name: changing Fingerprint Authentication to Fingerprint Authentication#1
11-07 16:37:51.292  1439 17048 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5804032
11-07 16:37:51.301  1439 17048 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5804032
11-07 16:37:51.308  1439  2118 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5804032
11-07 16:37:51.354 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:51.441 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:51.665 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:51.673 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:51.773 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:51.845 25838 25838 I chatty  : uid=10083(nl.demo.customer) identical 1 line
11-07 16:37:51.910 25838 25838 W zygote  : Attempt to remove non-JNI local reference, dumping thread
11-07 16:37:52.965 25838 25838 D SystemWebChromeClient: : Line 30 : Cancelled
11-07 16:37:52.965 25838 25838 I chromium: [INFO:CONSOLE(30)] "Cancelled", source:  (30)
11-07 16:37:52.971  1697  1697 V FingerprintService: stop client nl.demo.customer
11-07 16:37:52.971  1580  1580 D FingerprintHal: ----------------> fingerprint_cancel ----------------->
11-07 16:37:52.971  1580  1580 D android.hardware.biometrics.fingerprint@2.1-service: onError(5)
11-07 16:37:52.971  1697  1697 W FingerprintService: client nl.demo.customer is no longer authenticating
11-07 16:37:52.972  1697  1697 V FingerprintService: Done with client: nl.demo.customer
11-07 16:37:52.972  1697  1697 V FingerprintService: handleError(client=nl.demo.customer, error = 5)
11-07 16:37:52.988 25838 25912 D EGL_emulation: eglMakeCurrent: 0xf22e4a40: ver 3 0 (tinfo 0xe7a404e0)
11-07 16:37:53.777 24644 24653 E ReloadingLock: Finalizing LOCKED Token[shortcuts 2018-11-07 16:37:42.742]
11-07 16:37:53.973 24644 25137 I EventLogSendingHelper: Sending log events.
11-07 16:37:54.817 24604 24604 I BeaconBle: Scan : No clients left, canceling alarm.
11-07 16:37:55.762 25838 25992 I FirebaseCrash: Sending crashes
11-07 16:37:57.640  1431  1615 E audio_hw_generic: pcm_write failed cannot write stream data: I/O error
11-07 16:37:58.539  1580  1586 E FingerprintHal: fingerprint event listener at unexpected state 00
11-07 16:37:58.629  1580  1586 D FingerprintHal: fingerprint ID 0 off
11-07 16:37:58.885  1697  1713 E memtrack: Couldn't load memtrack module
11-07 16:37:58.885  1697  1713 W android.os.Debug: failed to get memory consumption info: -1
11-07 16:37:58.901  1697  1713 E memtrack: Couldn't load memtrack module
11-07 16:37:58.901  1697  1713 W android.os.Debug: failed to get memory consumption info: -1
11-07 16:37:59.350  1580  1586 E FingerprintHal: fingerprint event listener at unexpected state 00
11-07 16:37:59.438  1580  1586 D FingerprintHal: fingerprint ID 0 off
`

**Comment by NiklasMerz** [comment]
Maybe solved with the refactor of #179

**Comment by NiklasMerz** [comment]
Closed since #179 probably fixed this issue. Thank you for contributing!
