### ISSUE TITLE
Show an error message when the Swift version isn't correct

### ISSUE THREAD

**Issue by DydjyZ** [NiklasMerz/cordova-plugin-fingerprint-aio#115]
### Feature Request
Show an error message when the Swift version isn't correct
#### Feature Description

Hello,

It will be good to show an error when the Swift version isn't 3.X but 4.X, to prevent time wasting for searching the problem :) (Actually there is a silent error and the fingerprint won't show).

Dylan

**Comment by NiklasMerz** [comment]
I mostly run my builds with Xcode on a device or build it for deployment. If you open the project with XCode it will show an error.

**Comment by Liam-Ryan** [comment]
@NiklasMerz Does this mean that the plugin does not work with cordova-ios 5? ( xcode 10.2.1 required which in turn needs swift 4.0 minimum )

**Comment by NiklasMerz** [comment]
I think the plugin works with Swift 4. Did you try it? I run Xcode 10.2 without any problems.

**Comment by Liam-Ryan** [comment]
I've tried and we're not getting any response to calling isAvailable(), we are using Swift 5 but I don't think there's any issues between 4 & 5. I'll update to the latest now. You don't have the useswiftversion set to 3.2 still by any chance?

**Comment by NiklasMerz** [comment]
Did you set it in your projects config.xml?

**Comment by Liam-Ryan** [comment]
The problem is that if we set to swift 3.2 it's not available during the cordova build, we only have 4.0+ since updating to Mojave / Xcode 10.2.1. We can go to Xcode 10.1 or 9 and build with swift 3.2 with no issues but that will not build cordova-ios 5 for us ( 5.0.1 technically ). That's why I was asking for confirmation that the swift 3.2 is required still, it also says that on the npm page

I'll come back once I run the latest plugin, I don't see any obvious errors in xcode when it's set to swift 5. Should I open a new issue in case a pr comes from investigations?

**Comment by NiklasMerz** [comment]
No Swift 3.2 is not required. Just try setting the version in config.xml to 5 and see if it builds. We should probably raise the default version anyway.

**Comment by Liam-Ryan** [comment]
Thanks Niklas, I'm sorry for wasting your time on this one I just had to update to the latest version of the plugin and it worked :$
