### ISSUE TITLE
Is there a way to use device keychain to store/retrieve user password?

### ISSUE THREAD

**Issue by edubskiy** [NiklasMerz/cordova-plugin-fingerprint-aio#149]
### Feature Request
A way to use device keychain to store/retrieve user password?
#### Feature Description

Like "save" method in this plugin:
https://github.com/sjhoeksma/cordova-plugin-keychain-touch-id

**Comment by NiklasMerz** [comment]
I appreciate your suggestion. But I don´t think I will add something more like that.

This plugin is intended to be a simple authentication plugin. Why don´t you use this plugin instead? I would love to hear you feedback but I will close this because I think the other plugin already solves this.

**Comment by dractw** [comment]
@NiklasMerz Same issue here, that would be great to save/retrieve user credential from keychain for few reasons. Firstly first because there's many apps (including mine) where password uses not for auth only, but for encrypting users data (cryptowallets, keychains apps, etc), so in this case your plugin does just a half-deal, another half i should do by myself, encrypting user pass and store it somewhere, this's not so hardcode in there, but would be the awesome feature. Secondly, for security reasons, e.g. changing password when you should confirm old password by urself, or use the fingerprint with keychain to aprrove `Hey, it's me, here my old password` but not only `It's my biometrics here`, another case is banking-app where all sort of user actions should be approved by predefined user pin. 

Anyways, plugin is awesome, many thanks
