### ISSUE TITLE
Lockscreen Passcode is not opening if device do not support Fingerprint or Face detection

### ISSUE THREAD

**Issue by chinmay-ksolves** [NiklasMerz/cordova-plugin-fingerprint-aio#157]
## Description

Backup option as lock screen passcode verification is opened if users fail to verify their fingerprint after 5 attempts.
But this backup option is not available if the device does not support fingerprint or face detection functionality.

* Tested on Android 8.0 and IOS 12.1.4

**Comment by NiklasMerz** [comment]
I think this is intended behavior. You should check if the devices supports fingerprint. If not, you should offer a different method. Basically all apps I use do it this way.

**Comment by JanMisker** [comment]
At least on iOS it is possible to just call `Fingerprint.show({....})` and it will ask for the device Passcode. Makes sense to me to use that, instead of creating an app specific pin code.

I would really like it if this is also available for Android, it seems in the original Android plugin by mjwheatly this is added in this [commit](https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth/commit/7d2fbeec8b101be549118b0fe8e6620b89767e2d#diff-ee0bca0089cb64b4ee6bfa60e2b7544a) a while ago.

I will fork and create a PR for this.

**Comment by NiklasMerz** [comment]
Looking forward. I must admit that the Android part needs some care / catch up with the original one from mjwheatly. Any help is appreciated.
