### ISSUE TITLE
FaceID setup

### ISSUE THREAD

**Issue by roxxid** [NiklasMerz/cordova-plugin-fingerprint-aio#164]
The plugin directly logs in on successful faceID detection and executes the redirect code. 

How to handle username and password in this case? I searched through my dev phone for any signs of password or username being stored but couldnt find anything. Please do shed light on this.

```
.then((result: any) => {
   if(result == "Success"){
     //Fingerprint/Face was successfully verified
     //Go to dashboard
     this.navCtrl.push("DashboardPage")
    }
```

**Comment by NiklasMerz** [comment]
What do you mean with username and password? This plugin does not handle any credentials. It just shows a authentication prompt (touchid and faceid) and executes the callback if successfull. 

I am closing this now, because this is more a question and not an issue. If you have any questions feel free to use Gitter](https://gitter.im/cordova-plugin-fingerprint-aio).
