### ISSUE TITLE
LAContext evaluatePolicy does not always prompt user

### ISSUE THREAD

**Issue by paulstelzer** [NiklasMerz/cordova-plugin-fingerprint-aio#202]
## Description

There is a bug in iOS 13 and iOS 13.1 that the Touch ID not always shows up. That is a known bug that is fixed in iOS 13.2.

More information: https://forums.developer.apple.com/thread/121149 or https://stackoverflow.com/questions/35094167/lacontext-evaluatepolicy-does-not-always-prompt-user or https://twitter.com/JapieKrekel_/status/1177085074623389696

THe problem is that this plugin also uses the LAContext. But there is a workaround like described here to call it twice: https://stackoverflow.com/a/58409238

So this could be added to the Fingerprint.sift file before line 74:

```
let systemVersion = UIDevice.current.systemVersion
// Trick here: Try to do an pre-evaluate
if systemVersion.compare("13.0", options: .numeric) != .orderedAscending {
    authenticationContext.evaluatePolicy(policy, localizedReason: reason, reply: { (_, _) in
         //Ignore callback here
     })
}
```

All in all that's not an issue with this plugin, but maybe it would be nice to handle it. I can create a PR too if this is useful.

**Comment by NiklasMerz** [comment]
Thank you very much @paulstelzer for reporting this. I was wondering about this, too but before I got into this I switched to iOS 13.2 beta and completely forgot about that. The touchID prompt did not show up but it worked anyway.

Thank you for pointing out this fix, but I don't think this should be part of this plugin since it is an iOS bug that is now fixed. My goal is to support always the most recent version of iOS and keep the code as simple as possible.
