### ISSUE TITLE
Whitescreen on in-display fingerprint scanner

### ISSUE THREAD

**Issue by BorntraegerMarc** [NiklasMerz/cordova-plugin-fingerprint-aio#220]
## Description
On my OnePlus 6T with android 10 I get a white screen and don't see any of the title / description.

* What did you do?

Calling the library with ionic native like this:
```js
await this.fingerprint.show({
  title: 'test',
  description: 'test2'
});
```

* What did happen?
Saw a white screen on my OnePlus phone:
![Screenshot_20200121-100051](https://user-images.githubusercontent.com/7549295/72803945-9ea64080-3c4f-11ea-8549-f5c8d0a9dffb.jpg)

* What did you expect to happen?
That the title is displayed like on other android phones when there is a normal fingerprint scanner.

## Environment

* Plugin version 3.0.0

**Comment by NiklasMerz** [comment]
I use a OnePlus 6T myself and I am aware of this problem. Unfortunately we cannot do anything to fix this. This is bug in OnePlus' implemeation of the BiometricPrompt API of Android. See here: https://forums.oneplus.com/threads/problems-about-oneplus-6t-fingerprint-api.944959/ and here https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/179#issuecomment-542936744

The plugin switched to this new API since the old one is deprecated.

**Comment by NiklasMerz** [comment]
The plugin works just fine, but I understand that this is not pretty. I can see the same problem in other non Cordova apps I am using.

Thank you for using this plugin and reporting this issue.
