### ISSUE TITLE
Identify try again button trigger

### ISSUE THREAD

**Issue by WeiChun0723** [NiklasMerz/cordova-plugin-fingerprint-aio#291]
### Feature Request
Identify try again button trigger

#### Feature Description
Currently is there any function to identify the try again trigger in the below dialog ? 
![3333](https://user-images.githubusercontent.com/36685636/99631437-950b8600-2a76-11eb-9916-87090231bb03.jpg)

**Comment by NiklasMerz** [comment]
As far as I know the iOS API used here does not allow that.

Please check Apples documentation to see if we could add that: https://developer.apple.com/documentation/localauthentication/lapolicy/deviceownerauthenticationwithbiometrics

**Comment by WeiChun0723** [comment]
or is there something like counter to keep track how many times user has retry the finger print / face id ?

**Comment by NiklasMerz** [comment]
No as far as I know, because the OS handles this internally. iOS for
example allows 3 attempts. The Only gets called after the OS handles
this prompt. 

On November 19, 2020, GitHub <notifications@github.com> wrote:
> or is there something like counter to keep track how many times user

> has retry the finger print / face id ?
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/NiklasMerz/cordova-plugin-fingerprint-
aio/issues/291#issuecomment-730200484>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA3LOREUJDDFUDN2U7NHE73SQTGQLANCNFSM4T27REEQ>.

**Comment by WeiChun0723** [comment]
last question is i notice that when face id fail to recognize it wont return error message something like 'fail authenticate' or something similar ?

**Comment by NiklasMerz** [comment]
It should throw an error after many failed attempts

**Comment by WeiChun0723** [comment]
Hi Niklas,

May I know the secret in the register biometric secret function will be
encrypted within the function or we need to encrypt by ourself ?

**Comment by NiklasMerz** [comment]
Please keep the discussion in issues related to the issue.

Please check the README. There is a description what the secret parameter does and you could check to code if it does what you need.
