### ISSUE TITLE
"registerBiometricSecret" won't show authentication dialogue in IOS

### ISSUE THREAD

**Issue by cindylx0700** [NiklasMerz/cordova-plugin-fingerprint-aio#297]
### Bug report
With the latest version plugin, "registerBiometricSecret" won't show authentication dialogue in IOS. Android is all good. 

## Description

My function just like below (same as the example), working perfect on Android device, but the authentication dialogue won't displayed on IOS. Tested on both iOS 14.2, and IOS 12.4.9.  The secret function looks working well, as I got the "success" response from the register Biometric secret function, and also got expected string response from loadBiometricSecret function. Just the authentication dialogue for register never shown in IOS. 

return  this.faio.registerBiometricSecret({
      description: 'hello',
      secret: 'some-secret',
    });

Plugin version is the latest version 4.0.1, 
cordova-ios: "6.1.0", 
cordova-android: "9.0.0",
@ionic-native/fingerprint-aio: "5.29.0"
cordova-plugin-fingerprint-aio: "4.0.1"

**Comment by grandfather1** [comment]
I have also the same issue

**Comment by NiklasMerz** [comment]
I don't think you would need to authenticate for registering the secret. That's just how iOS works.

**Comment by rbtprograms** [comment]
I am confused as to why this was closed. I am currently having this same issue, are you saying that registerBiometricSecret should should the dialogue on android and not iOs? How are these new secret registering/loading functions supposed to work on the different platforms?

**Comment by AbdulAhad125** [comment]
Yes same problem and can we store multiple secrets.

**Comment by NiklasMerz** [comment]
This plugin just uses the APIs Android and iOS offers. If iOS can store the secret without showing the dialog this works as designed. If the secret gets stored and can be loaded afterwards this is fine. Android and iOS work quite differently but as long as the API of this plugin is the same it's working as designed.

**Comment by rbtprograms** [comment]
So the registerBiometricSecret is not supposed to show the authentication dialogue? I have posted a screen shot of your own documentation for this project below.

<img width="863" alt="Screen Shot 2021-03-03 at 9 01 14 AM" src="https://user-images.githubusercontent.com/37790245/109869915-52814a00-7c1e-11eb-97a0-bbc139435e7b.png">

I am confused by your response, because in your documentation is certainly says to show the dialogue and register the secret. However, your response tells me that you think it should not show the dialogue, and that iOS can save a secret without showing the dialogue. 

How is this method intended to function? The documentation makes it sound like it would show the dialogue and register a secret that could be then be blown away if a new fingerprint/face is registered. However, it doesn't work like that at all and you seem to agree that it doesn't work that way. How exactly is this supposed to function?

**Comment by NiklasMerz** [comment]
I didn't build this feature myself and did not wrote the documentation https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/236/files. This is a community contribution. As I am not using it in production and don't know the details of the APIs, I think it works as designed. Documentation can be wrong. You can go in the code and look up the APIs behind it.

If it doesn't fit your need you can always change it in your own fork. I welcome any contributions for better documentation and maybe changes to how it works if I think they fit the project.

This is an open source project originally built for personal use. Over the time many contributions changed it. I don't know everything about it and honestly don't have the time and motivation to work deeply on this as I am not getting paid to do this.

**Comment by rbtprograms** [comment]
Yea, I definitely understand that it can be a lot to maintain open source projects when not being paid for it. I decided not to use this package because these methods have some clearly odd behaviors, and I just decided to roll my own plugin. I would like to point out that you did say something odd though

```
Documentation can be wrong.
```

This is a puzzling, if not troubling thing to hear. I understand you are not paid to maintain this project and you did not write the code, but actively saying that "yes, documentation doesn't have to be correct" is, at best, a strange thing to say. It's actively misguiding people who are arriving at your package and misrepresenting what the package is capable of. If you don't want to maintain the project then that is fine, but openly having incorrect documentation and writing it off as something normal is a rough take.

**Comment by NiklasMerz** [comment]
Thank you for the feedback for the incorrect documentation. I just did a tiny edit: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/commit/9dae455134ac06a2e7bd963655b233ef8efc58cd. I definitely don't want misleading documentation but it can happen. This issue shows this confused some people and we should fix it.

Sorry if I sound rude or something.

**Comment by rbtprograms** [comment]
No problem, and thanks for making that change! I never thought your responses were rude, and I hope I came across as respectful as well. Thanks for doing this, I appreciate your work on this package and it helped me when making a plugin as well.

**Comment by AbdulAhad125** [comment]
It is now showing to me first time only but after multiple try it open and register in ios.

**Comment by NiklasMerz** [comment]
Somwhat related: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/305#issuecomment-802279541
