### ISSUE TITLE
fingerprint aio is not respecting other plugins swift headers. Therefore making it difficult to use it with other plugins

### ISSUE THREAD

**Issue by MishraAarambh** [NiklasMerz/cordova-plugin-fingerprint-aio#335]
## Description
the fingerprint plugin is creating conflicting with other plugins swift headers
because of this iosrtc plugin stopped working 

* What did you do?
Added this plugin with iosrtc plugin
* What did happen?
Build failure in ios
Build fail with plugin. The target "appName" contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets
* What did you expect to happen?
Build success

## Environment

* Plugin version
Latest
* Build environment (```cordova info```)
cordova 10.0.0

### Logs
XCode shows this error
<details>
  <pre>The target "appName" contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets</pre>
</details>

**Comment by hthetiot** [comment]
Steps to reproduces:

 -  cordova create myApp org.apache.cordova.myApp myApp; cd myApp;
  - cordova platform add ios@latest --verbose
  - cordova plugin add cordova-plugin-iostrtc --verbose
  - cordova plugin add cordova-plugin-fingerprint-aio --verbose
  - cordova prepare ios --verbose
  - Open Xcode Project

Results:

<img width="330" alt="Screenshot 2021-03-22 at 21 49 36" src="https://user-images.githubusercontent.com/8635/112059422-1c1f5680-8b5c-11eb-882e-83338f51adf5.png">

The reason is this plugin overide swift version and swift headers instead of merging them.
If you looking for a proper way to merge headers and edit sift version I recommand to add a plugin.xml after_prepare hook like iosrtc does here:

- https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/plugin.xml#L23
- https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/extra/hooks/iosrtc-swift-support.js#L373

I'm the maintainer of cordova-plugin-iosrtc and i can confirm we play nice with other plugins, for reference we tests this plugins on each release to make sure we are compatible with others plugins.


    "cordova-custom-config": "^5.1.0",
    "cordova-plugin-android-permissions": "^1.1.0",
    "cordova-plugin-androidx": "^2.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.1",
    "cordova-plugin-audioroute": "^0.1.2",
    "cordova-plugin-background-mode": "^0.7.3",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-customurlscheme": "^5.0.2",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-plugin-insomnia": "^4.3.0",
    "cordova-plugin-keyboard": "^1.2.0",
    "cordova-plugin-media": "^5.0.3",
    "cordova-plugin-media-capture": "^3.0.3",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-safariviewcontroller": "^1.6.0",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-settings-hook": "^0.3.1",
    "cordova-plugin-splashscreen": "^6.0.0",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-support-google-services": "^1.3.2",
    "cordova.plugins.diagnostic": "^6.0.2",
    "es6-promise-plugin": "^4.2.2",
    "phonegap-plugin-multidex": "^1.0.0",
    "cordova-plugin-facebook4": "^6.4.0",
    "cordova-plugin-whitelist": "^1.3.4",
    "phonegap-plugin-push": "^2.3.0"

**Comment by dmitry-salnikov** [comment]
related issue https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/342

**Comment by NiklasMerz** [comment]
Thank your for reporting the issue. Please test the lates version 5.0.0 and make sure to add the version for config.xml
