### ISSUE TITLE
Unable to build in http://build.phonegap.com

### ISSUE THREAD

**Issue by dhivehi** [NiklasMerz/cordova-plugin-fingerprint-aio#47]
With this plugin, I'm always getting swift error in http://build.phonegap.com. Couldnt build app.. Even if i define swift version in config.xml as defined in readme. Please help

**Comment by NiklasMerz** [comment]
I never tried phonegap build with this plugin. Have you tried adding the master branch of this repo to your project? I just changed the dependency of swift support? Could you please provide logs? Build logs, Plugin versions etc.

**Comment by dhivehi** [comment]
Hello, here's the log generated by http://build.phonegap.com

[build.txt](https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/files/1268088/build.txt)

**Comment by NiklasMerz** [comment]
Please try removing and adding the plugin again. The swift version is only set while installing. Please verify that the swift version which is supported by Phonegap build.

**Comment by DavidTalamona** [comment]
Think this is could be the same reason I have with my project, see https://github.com/akofman/cordova-plugin-add-swift-support/issues/34/#issuecomment-327806538.

Not sure if this problem is related to the Fingerprint or the Swift-Support plugin but it seems to pop up since xcode 8.3.3.
If you search the internet, there's many people complaining about the same problems at different plugins, all using Swift.

**Comment by NiklasMerz** [comment]
I have also some issues with building on newer XCode versions. For me setting the correct Swift version in XCode solves this. But for Phonegap build the issue needs be resolved wwith the Swift support plugin.

**Comment by NiklasMerz** [comment]
I am closing this now, since this seems to be problem of the Swift support plugin.

Feel free to open this issue again if you have any news on this error.
