### ISSUE TITLE
Samsung Device with FaceID not working 

### ISSUE THREAD

**Issue by scotthmusson** [NiklasMerz/cordova-plugin-fingerprint-aio#473]
## Description

Plug 5.0.1
Android cordova 11.0

Using the method registerBiometricSecret on a Samsung device with the ability to register face recognition and fingerprints, if no fingerprint is registered, get a java error back from this method.  If I add a fingerprint, the device behaves correctly using the fingerprint.  

FaceID works fine on iOS with registerBiometricSecret, I would expect I could do the same with Android.

I appreciate any assistance with this issue, I really appreciate this plugin and I'm trying to migrate to use the stored secret methods.

### Logs

<details>
  <pre>{code: -100, message: 'java.lang.IllegalStateException: At least one biom… keys requiring user authentication for every use'}
code
: 
-100
message
: 
"java.lang.IllegalStateException: At least one biometric must be enrolled to create keys requiring user authentication for every use"</pre>
</details>

**Comment by austinwark** [comment]
This is due to the usage of deprecated `BiometricManager.canAuthenticate()` (in Fingerprint.java). If we were to instead use `canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_STRONG)`, an Android phone with just face ID enrolled would return `PluginError.BIOMETRIC_NOT_ENROLLED`.

**Comment by NiklasMerz** [comment]
Thanks @austinwark for the pointers.

I created #477 to replace the deprecated call. But I also could create a new breaking major version to require STRONG biometrics. Not sure about that, yet.

**Comment by scotthmusson** [comment]
Getting a build error with new version:

cordova/platforms/android/app/src/main/java/de/niklasmerz/cordova/biometric/Fingerprint.java:139: error: ';' expected
     [exec]         int error = BiometricManager.from(cordova.getContext()).canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_WEAK)
     [exec]                                                                                                                                ^
     [exec] 1 error
     [exec] 
     [exec] FAILURE: Build failed with an exception.

**Comment by NiklasMerz** [comment]
Sorry got a syntax error. 5.0.3 should build.

**Comment by austinwark** [comment]
Thanks for your time @NiklasMerz. However, I'm afraid your addition in #477 will not solve the problem @scotthmusson and I are seeing.

The underlying issue is the `registerBiometricSecret` and `loadBiometricSecret` methods use BiometricManager methods that are incompatible with "Weak" biometrics - [See Android Docs](https://developer.android.com/reference/androidx/biometric/BiometricPrompt#authenticate(androidx.biometric.BiometricPrompt.PromptInfo,androidx.biometric.BiometricPrompt.CryptoObject)).

However, when `isAvailable` is called, it does not check the biometric strength. So when a device with just face ID enrolled calls `isAvailable()` it will pass, even though the face ID is not supported by the methods that register biometric secrets.

I whipped up a possible solution to this (I'm sure it can be improved if need be), see pull request #480. Thanks again.
